configuration and makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,8 +4,8 @@
 #*    -------------------------------------------------------------    */
 #*    Author      :  Manuel Serrano                                    */
 #*    Creation    :  Sat Jul 31 06:49:37 2004                          */
-#*    Last change :  Mon Oct  9 16:35:38 2017 (serrano)                */
-#*    Copyright   :  2004-17 Manuel Serrano                            */
+#*    Last change :  Mon Feb  5 18:08:43 2018 (serrano)                */
+#*    Copyright   :  2004-18 Manuel Serrano                            */
 #*    -------------------------------------------------------------    */
 #*    HOPSTMP autoconfiguration                                        */
 #*=====================================================================*/
@@ -66,11 +66,14 @@ while : ; do
       hflags="`echo $1 | sed 's/^[^=]*=//'`"/$mansec;;
 
     -*)
-      echo "*** Configure error, unknown option $1" >&2;
-      echo >&2;
+      if [ $1 != "--help" ]; then
+        echo "*** Configure error, unknown option $1" >&2;
+        echo >&2;
+      fi
       echo "Usage: configure [options]" >&2;
       echo "" >&2;
       echo "options:" >&2;
+      echo "   --help..................... this message" >&2;
       echo "   --hop=path................. hop command" >&2;
       echo "   --hopc=path................ hopc command" >&2;
       echo "   --hflags=flags............. hopc flags" >&2;
